// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelFile(arg1) {
  return window['go']['main']['App']['CancelFile'](arg1);
}

export function ConvertFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConvertFile'](arg1, arg2, arg3, arg4);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectFolderFiles() {
  return window['go']['main']['App']['SelectFolderFiles']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}
