// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelFile(arg1:string):Promise<void>;

export function ConvertFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolderFiles():Promise<Array<string>>;

export function SelectOutputDir():Promise<string>;
