// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {decoder} from '../models';

export function CancelFile(arg1:string):Promise<void>;

export function CheckLocalQQMusicLogin(arg1:string):Promise<decoder.QQCookieCheckResult>;

export function CheckQQMusicCookie(arg1:string,arg2:string):Promise<decoder.QQCookieCheckResult>;

export function ClearQQLoginCache():Promise<void>;

export function ConvertFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean):Promise<string>;

export function GetDefaultOutputDir():Promise<string>;

export function GetRuntimePlatform():Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolderFiles():Promise<Array<string>>;

export function SelectOutputDir():Promise<string>;
